### ISSUE TITLE
Bot doesn't leave VC when player is destroyed

### ISSUE THREAD

**Issue by lumap** [lavaclient/lavadeno#7]
The player.destroy function used to be async and disconnected the bot from the voice channel it was in. With 3.0.1, it's not async and doesn't make the bot leave.

**Comment by viztea** [comment]
`Player#destroy()` does what its supposed to, if you want to make the bot leave call disconnect before destroy. 

*also it's still async*

**Comment by viztea** [comment]
Unless there's a high demand for destroy to disconnect from the vc, you'll have to do it yourself.
