### ISSUE TITLE
Emit some player event when bot gets kicked from voice channel

### ISSUE THREAD

**Issue by zabihexes** [lavaclient/lavadeno#8]
I did not find any way to detect this via existing player events.

Before the rewrite it was possible to detect this via this code.
```ts
// Handle if bot gets kicked from the voice channel
  player.once("closed", async () => {
    await bot.lavadenoManager.destroy(message.guildId.toString());
    await message.send("I have been disconnected from the channel.");
  });
```

Thanks

**Comment by viztea** [comment]
Thanks for creating an issue. I need to add the websocket closed event to the [lavalink-types repo](https://github.com/lavaclient/lavalink_types), then I'll add this event. 

Sorry for the inconvenience

**Comment by zabihexes** [comment]
> Thanks for creating an issue. I need to add the websocket closed event to the [lavalink-types repo](https://github.com/lavaclient/lavalink_types), then I'll add this event.
> 
> Sorry for the inconvenience

No problem.  :+1:

**Comment by viztea** [comment]
Added in latest commit 👌🏼
